/**
 * srcset helpers for game images. Variants are generated by
 * scripts/game-image-variants.sh and checked at build by scripts/check-assets.mjs.
 */

/** "/games/x/icon-512.webp" -> 128/256/512 variants. */
export function iconSrcSet(icon: string) {
  if (!icon.endsWith("-512.webp")) return undefined;
  const base = icon.slice(0, -"-512.webp".length);
  return `${base}-128.webp 128w, ${base}-256.webp 256w, ${icon} 512w`;
}

/** "/games/x/screen-1.webp" (800px) -> 480px variant + original. */
export function screenSrcSet(shot: { src: string; width: number }) {
  return `${shot.src.replace(/\.webp$/, "-480.webp")} 480w, ${shot.src} ${shot.width}w`;
}
